export const data = {
    names: [
        {name: "팔광", gender: "M", feature: "쎄보이는"},
        {name: "억두", gender: "M", feature: "쎄보이는"},
        {name: "혁팔", gender: "M", feature: "쎄보이는"},
        {name: "팔식", gender: "M", feature: "쎄보이는"},
        {name: "두식", gender: "M", feature: "쎄보이는"},
        {name: "무혁", gender: "M", feature: "쎄보이는"},
        {name: "암철", gender: "M", feature: "쎄보이는"},
        {name: "철혁", gender: "M", feature: "쎄보이는"},
        {name: "철혁", gender: "M", feature: "쎄보이는"},
        {name: "철옥", gender: "F", feature: "쎄보이는"},
        {name: "쎄리", gender: "F", feature: "쎄보이는"},
        {name: "철숙", gender: "F", feature: "쎄보이는"},
        {name: "팔숙", gender: "F", feature: "쎄보이는"},
        {name: "두옥", gender: "F", feature: "쎄보이는"},
        {name: "두옥", gender: "F", feature: "쎄보이는"},
        {name: "춘배", gender: "M", feature: "촌스러운"},
        {name: "춘삼", gender: "M", feature: "촌스러운"},
        {name: "덕배", gender: "M", feature: "촌스러운"},
        {name: "춘섭", gender: "M", feature: "촌스러운"},
        {name: "복남", gender: "M", feature: "촌스러운"},
        {name: "팔봉", gender: "M", feature: "촌스러운"},
        {name: "봉팔", gender: "M", feature: "촌스러운"},
        {name: "덕구", gender: "M", feature: "촌스러운"},
        {name: "영배", gender: "M", feature: "촌스러운"},
        {name: "점순", gender: "F", feature: "촌스러운"},
        {name: "춘자", gender: "F", feature: "촌스러운"},
        {name: "봉순", gender: "F", feature: "촌스러운"},
        {name: "점복", gender: "F", feature: "촌스러운"},
        {name: "금례", gender: "F", feature: "촌스러운"},
        {name: "금자", gender: "F", feature: "촌스러운"},
    ],
    locations: [
        {name: "도서관", suffix_group_index: 0},
        {name: "시험장", suffix_group_index: 0},
        {name: "공부방", suffix_group_index: 0},
        {name: "경로당", suffix_group_index: 1},
        {name: "노인정", suffix_group_index: 1},
        {name: "어린이집", suffix_group_index: 2},
        {name: "유치원", suffix_group_index: 2},
    ],
    suffix_groups: [
        [["박수", "라디오", "휘파람"], ["빌런"]],
        [["지팡이", "휠체어"], ["도둑", "파괴범"]],
        [["가방", "장난감"], ["도둑", "파괴범"]]
    ],
};