export const data = {
    names: [
        {name: "팔광", gender: "M", feature: "쎄보이는"},
        {name: "억두", gender: "M", feature: "쎄보이는"},
        {name: "혁팔", gender: "M", feature: "쎄보이는"},
        {name: "팔식", gender: "M", feature: "쎄보이는"},
        {name: "두식", gender: "M", feature: "쎄보이는"},
        {name: "무혁", gender: "M", feature: "쎄보이는"},
        {name: "암철", gender: "M", feature: "쎄보이는"},
        {name: "철혁", gender: "M", feature: "쎄보이는"},
        {name: "철혁", gender: "M", feature: "쎄보이는"},
        {name: "철옥", gender: "F", feature: "쎄보이는"},
        {name: "쎄리", gender: "F", feature: "쎄보이는"},
        {name: "철숙", gender: "F", feature: "쎄보이는"},
        {name: "팔숙", gender: "F", feature: "쎄보이는"},
        {name: "두옥", gender: "F", feature: "쎄보이는"},
        {name: "두옥", gender: "F", feature: "쎄보이는"},
        {name: "춘배", gender: "M", feature: "촌스러운"},
        {name: "춘삼", gender: "M", feature: "촌스러운"},
        {name: "덕배", gender: "M", feature: "촌스러운"},
        {name: "춘섭", gender: "M", feature: "촌스러운"},
        {name: "복남", gender: "M", feature: "촌스러운"},
        {name: "팔봉", gender: "M", feature: "촌스러운"},
        {name: "봉팔", gender: "M", feature: "촌스러운"},
        {name: "덕구", gender: "M", feature: "촌스러운"},
        {name: "영배", gender: "M", feature: "촌스러운"},
        {name: "점순", gender: "F", feature: "촌스러운"},
        {name: "춘자", gender: "F", feature: "촌스러운"},
        {name: "봉순", gender: "F", feature: "촌스러운"},
        {name: "점복", gender: "F", feature: "촌스러운"},
        {name: "금례", gender: "F", feature: "촌스러운"},
        {name: "금자", gender: "F", feature: "촌스러운"},
    ],
    familyNames: [
        "김",
        "이",
        "박",
        "최",
        "정",
        "강",
        "조",
        "윤",
        "장",
        "임",
        "한",
        "오",
        "서",
        "신",
        "권",
        "황",
        "안",
        "송",
        "전",
        "홍",
        "유",
        "고",
        "문",
        "양",
        "손",
        "배",
        "조",
        "백",
        "허",
        "남",
        "마",
    ],
    locations: [
        {
            name: "도서관",
            suffixGroup: [["박수", "휘파람"], ["빌런"]],
        },
        {
            name: "시험장",
            suffixGroup: [["박수", "휘파람"], ["빌런"]],
        },
        {
            name: "공부방",
            suffixGroup: [["박수", "휘파람"], ["빌런"]],
        },
        {
            name: "경로당",
            suffixGroup: [["지팡이", "틀니"], ["도둑", "파괴범", "절도범"]],
        },
        {
            name: "노인정",
            suffixGroup: [["지팡이", "틀니"], ["도둑", "파괴범", "절도범"]],
        },
        {
            name: "어린이집",
            suffixGroup: [["가방", "장난감"], ["도둑", "절도범"]],
        },
        {
            name: "유치원",
            suffixGroup: [["가방", "장난감"], ["도둑", "절도범"]],
        },
        {
            name: "길거리",
            suffixGroup: [["자전거", "킥보드"], ["뺑소니", "절도범", "도둑"]],
        },
        {
            name: "급식실",
            suffixGroup: [["잔반", "음쓰"], ["처리반", "시식가"]],
        },
        {
            name: "납골당",
            suffixGroup: [["유골"], ["도둑", "절도범"]],
        },
        {
            name: "교회",
            suffixGroup: [["목탁"], ["연주자"]],
        },
        {
            name: "성당",
            suffixGroup: [["목탁"], ["연주자"]],
        },
        {
            name: "목욕탕",
            suffixGroup: [["비누", "수건"], ["도둑", "절도범"]],
        },
        {
            name: "키즈카페",
            suffixGroup: [["인형", "장난감"], ["도둑", "절도범"]],
        },
        {
            name: "피시방",
            suffixGroup: [["모니터", "키보드", "마우스"], ["도둑", "샷건러", "파괴범", "절도범"]],
        },
        {
            name: "화장실",
            suffixGroup: [["세면기", "소변기"], ["똥", "설사", "오줌"], ["테러범"]],
        },
        {
            name: "금연구역",
            suffixGroup: [["담배꽁초"], ["테러범", "빌런"]],
        },
        {
            name: "공원",
            suffixGroup: [["개똥"], ["테러범", "빌런"]],
        },
        {
            name: "훈련소",
            suffixGroup: [["탄피"], ["분실범"]],
        },
        {
            name: "헬스장",
            suffixGroup: [["아령"], ["도둑", "절도범"]],
        },
        {
            name: "수영장",
            suffixGroup: [["오줌"], ["테러범"]],
        },
        {
            name: "지하철",
            suffixGroup: [["게르마늄 팔찌", "코고리 마스크"], ["판매원"]],
        },
        {
            name: "병원",
            suffixGroup: [["붕대", "코고리 마스크"], ["도둑", "절도범"]],
        },
    ],
};